### PR TITLE
chore: folders structure

### PR DESCRIPTION
**Pull request by marcioandrews**

### CODE REVIEW

**Review by MarcioOrdonez — CHANGES_REQUESTED** [review]
You must add `node_modules` into the `.gitignore` list

**Comment by MarcioOrdonez** [comment]
The PR name should follow the same pattern we discussed before eg: `chore: folders structure`

**Comment by marcioandrews** [comment]
Fixed and done, check please.

**Review by MarcioOrdonez — COMMENTED** [review]
LGTM

**Pull request merged**
